#!/bin/sh

main() {
    CMD="$1"
    X=$2
    Y=$3
    MW=$4
    MH=$5
    FILE="$(readlink -f "$PWD/$6")"
    CACHE="$XDG_CACHE_HOME/ueberzugpp/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$FILE" | sha512sum).jpg"
    CACHE="${CACHE%% *}"

    case "$CMD" in
        "clear") clear; exit;;
        "draw") CACHE="$FILE";;
        "video") [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$FILE" -o "$CACHE" -s 0 -q 5;;
        "audio") [ ! -f "$CACHE" ] && ffmpeg -hide_banner -i "$FILE" "$CACHE" -y >/dev/null;;
        "pdf")   [ ! -f "$CACHE" ] && pdftoppm -jpeg -f 1 -singlefile "$FILE" "$CACHE";;
        "epub")  [ ! -f "$CACHE" ] && epub-thumbnailer "$FILE" "$CACHE" 720;;
        "djvu")  [ ! -f "$CACHE" ] && ddjvu -format=tiff -quality=90 -page=1 "$FILE" "$CACHE";;
        "font")  [ ! -f "$CACHE" ] && fontpreview -i "$FILE" -o "$CACHE";;
        "cbz"|"cbt"|"cb7"|"cbr") [ ! -f "$CACHE" ] && cache_first_image;;
        *) exit 1;;
    esac

    image "$X" "$Y" "$MW" "$MH" "$CACHE"
}

image() {
    ueberzugpp cmd -s "$UB_SOCKET" -a add -i PREVIEW \
        -x "$1" -y "$2" --max-width "$3" --max-height "$4" -f "$5"
}

clear() {
    ueberzugpp cmd -s "$UB_SOCKET" -a remove -i PREVIEW
}

cache_first_image() {
    tmpdir="$(mktemp --directory)"
    cleanup() { fusermount -u "$1" && rm -rf "$1"; }
    trap "cleanup $tmpdir" EXIT

    case "$CMD" in
        "cbz") fuse-zip -r "$FILE" "$tmpdir";;
        "cbt") archivemount "$FILE" "$tmpdir" -o readonly;;
        "cb7") fuse3-p7zip "$FILE" "$tmpdir";;
        "cbr") rar2fs "$FILE" "$tmpdir";;
    esac

    first_image="$(find "$tmpdir" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.webp" \) | sort | head -1)"
    convert -thumbnail 720 "$first_image" "$CACHE"
}

main "$@"
