#!/bin/sh

set -e

if [ -z "$(command -v vifm)" ]; then
    printf "vifm isn't installed on your system!\n"
    exit 1
elif [ -z "$(command -v ueberzugpp)" ]; then
    exec vifm "$@"
else
    UB_PID=0
    UB_SOCKET=""

    cleanup() {
        tput clear
        ueberzugpp cmd -s "$UB_SOCKET" -a exit
    }
    trap cleanup HUP INT QUIT TERM PWR EXIT

    UB_PID_FILE="/tmp/.$(uuidgen)"
    ueberzugpp layer --no-cache --no-stdin --silent --use-escape-codes \
        --pid-file "$UB_PID_FILE"
    UB_PID="$(cat "$UB_PID_FILE")"
    export UB_SOCKET=/tmp/ueberzugpp-"$UB_PID".socket

    vifm "$@" 3>&-
    vifmimg clear
fi
